/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Item = IDL.Record({ 'name' : IDL.Text, 'typeId' : IDL.Nat32 });
export const Prefab = IDL.Record({
  'name' : IDL.Text,
  'position' : IDL.Text,
  'prefabId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AvailableProcesses = IDL.Record({
  'lastUpdated' : Time,
  'processes' : IDL.Vec(IDL.Text),
});
export const ModSettings = IDL.Record({
  'superSpeedEnabled' : IDL.Bool,
  'superJumpMultiplier' : IDL.Float64,
  'disableMonsters' : IDL.Bool,
  'superJumpEnabled' : IDL.Bool,
  'flyEnabled' : IDL.Bool,
  'superSpeedMultiplier' : IDL.Float64,
});
export const ProcessSelector = IDL.Record({
  'selectedProcess' : IDL.Opt(IDL.Text),
});
export const PrefabSpawner = IDL.Record({
  'prefabs' : IDL.Vec(Prefab),
  'spawnHistory' : IDL.Vec(IDL.Text),
});
export const ItemSpawner = IDL.Record({
  'spawnHistory' : IDL.Vec(IDL.Text),
  'items' : IDL.Vec(Item),
});
export const UserProfile = IDL.Record({
  'modSettings' : ModSettings,
  'processSelector' : ProcessSelector,
  'name' : IDL.Text,
  'prefabSpawner' : PrefabSpawner,
  'itemSpawner' : ItemSpawner,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItem' : IDL.Func([Item], [], []),
  'addPrefab' : IDL.Func([Prefab], [], []),
  'addPrefabSpawnHistory' : IDL.Func([IDL.Text], [], []),
  'addSpawnHistory' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearItems' : IDL.Func([], [], []),
  'clearPrefabs' : IDL.Func([], [], []),
  'getAvailableProcesses' : IDL.Func([], [AvailableProcesses], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItemSpawner' : IDL.Func([], [IDL.Opt(ItemSpawner)], ['query']),
  'getModSettings' : IDL.Func([], [ModSettings], ['query']),
  'getPrefabSpawner' : IDL.Func([], [IDL.Opt(PrefabSpawner)], ['query']),
  'getProcessSelector' : IDL.Func([], [ProcessSelector], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setProcessSelector' : IDL.Func([ProcessSelector], [], []),
  'updateAvailableProcesses' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateModSettings' : IDL.Func([ModSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Item = IDL.Record({ 'name' : IDL.Text, 'typeId' : IDL.Nat32 });
  const Prefab = IDL.Record({
    'name' : IDL.Text,
    'position' : IDL.Text,
    'prefabId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AvailableProcesses = IDL.Record({
    'lastUpdated' : Time,
    'processes' : IDL.Vec(IDL.Text),
  });
  const ModSettings = IDL.Record({
    'superSpeedEnabled' : IDL.Bool,
    'superJumpMultiplier' : IDL.Float64,
    'disableMonsters' : IDL.Bool,
    'superJumpEnabled' : IDL.Bool,
    'flyEnabled' : IDL.Bool,
    'superSpeedMultiplier' : IDL.Float64,
  });
  const ProcessSelector = IDL.Record({ 'selectedProcess' : IDL.Opt(IDL.Text) });
  const PrefabSpawner = IDL.Record({
    'prefabs' : IDL.Vec(Prefab),
    'spawnHistory' : IDL.Vec(IDL.Text),
  });
  const ItemSpawner = IDL.Record({
    'spawnHistory' : IDL.Vec(IDL.Text),
    'items' : IDL.Vec(Item),
  });
  const UserProfile = IDL.Record({
    'modSettings' : ModSettings,
    'processSelector' : ProcessSelector,
    'name' : IDL.Text,
    'prefabSpawner' : PrefabSpawner,
    'itemSpawner' : ItemSpawner,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItem' : IDL.Func([Item], [], []),
    'addPrefab' : IDL.Func([Prefab], [], []),
    'addPrefabSpawnHistory' : IDL.Func([IDL.Text], [], []),
    'addSpawnHistory' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearItems' : IDL.Func([], [], []),
    'clearPrefabs' : IDL.Func([], [], []),
    'getAvailableProcesses' : IDL.Func([], [AvailableProcesses], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItemSpawner' : IDL.Func([], [IDL.Opt(ItemSpawner)], ['query']),
    'getModSettings' : IDL.Func([], [ModSettings], ['query']),
    'getPrefabSpawner' : IDL.Func([], [IDL.Opt(PrefabSpawner)], ['query']),
    'getProcessSelector' : IDL.Func([], [ProcessSelector], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setProcessSelector' : IDL.Func([ProcessSelector], [], []),
    'updateAvailableProcesses' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateModSettings' : IDL.Func([ModSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };